"""
DocsMind - Evaluation Telemetry
Automated LLM-as-a-judge testing framework for evaluating RAG performance.
"""

from pipeline import DocsMindPipeline
from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

def run_evaluation_suite():
    print("Initializing Evaluation Suite...")
    
    # 1. Initialize our existing pipeline
    # Ensure you have already processed a document into chroma_db before running this!
    app_pipeline = DocsMindPipeline()
    if not app_pipeline.vector_db:
        print("Error: No database found. Please run app.py and process a document first.")
        return

    # 2. Setup the Evaluator LLM (The "Judge")
    # We use temperature 0.0 for strict, analytical grading.
    evaluator_llm = ChatOllama(model="gemma2:2b", temperature=0.0)

    # 3. Define our test cases
    # Add questions and the answers you *expect* the system to provide.
    test_cases = [
        {
            "query": "What are the core features mentioned in the document?",
            "expected_answer": "It mentions document loading, vector storage, and conversational memory."
        },
        # Add more test cases based on the specific PDF you uploaded
    ]

    # 4. Define the Evaluation Prompt
    evaluation_prompt = PromptTemplate.from_template(
        """
        You are an impartial evaluator grading a RAG (Retrieval-Augmented Generation) system.
        
        Question asked by user: {query}
        Expected Answer: {expected}
        Actual Answer generated by system: {actual}
        
        Evaluate the Actual Answer based on these two metrics:
        1. Answer Relevance (1-5): Does it directly address the user's question?
        2. Faithfulness (1-5): Does it align with the facts in the Expected Answer without hallucinating?
        
        Output your evaluation EXACTLY in this format:
        Relevance Score: [1-5]
        Faithfulness Score: [1-5]
        Reasoning: [1 sentence explaining why]
        """
    )
    
    eval_chain = evaluation_prompt | evaluator_llm | StrOutputParser()

    print("\nStarting Tests...\n" + "="*40)

    # 5. Execute the tests
    for i, test in enumerate(test_cases, 1):
        print(f"\nRunning Test Case {i}: '{test['query']}'")
        
        # Get the actual output from our pipeline
        # (We join the stream generator into a single string)
        stream = app_pipeline.chat_stream(test["query"], session_id=f"test_session_{i}")
        actual_output = "".join([chunk for chunk in stream])
        
        print(f"System Output: {actual_output.strip()[:100]}...")
        
        # Grade the output
        print("Grading...")
        score_report = eval_chain.invoke({
            "query": test["query"],
            "expected": test["expected_answer"],
            "actual": actual_output
        })
        
        print("\n--- Evaluation Report ---")
        print(score_report)
        print("="*40)

if __name__ == "__main__":
    run_evaluation_suite()